### ISSUE TITLE
Minor bug when packet doesn't have body

### ISSUE THREAD

**Issue by Zduniusz** [libwifi/libwifi#16]
Function `libwifi_get_wifi_frame` tries to allocate 0 bytes of space for packets that have only mac header

https://github.com/libwifi/libwifi/blob/e87c63db4a2ae4b2ddeefc00ed9ae4669333d016/src/libwifi/core/frame/frame.c#L129

Steps to reproduce:
Call `libwifi_get_wifi_frame` with packet that have same `frame_data_len` as `header_len` 

Example:
```
//Null function packet that have no body
char packet_bytes[] = {
  0x48, 0x19, 0x3c, 0x00, 0x30, 0xb5, 0xc2, 0xe3,
  0x14, 0x8a, 0x06, 0x95, 0xa3, 0x4c, 0x2b, 0x68,
  0x30, 0xb5, 0xc2, 0xe3, 0x14, 0x8a, 0x00, 0x90
};
```

**Comment by foxtrot** [comment]
Hi,

Thanks for the report. I am curious, do you see a crash with this? While it'd be wise to avoid a malloc(0), this shouldn't cause an error. If it does, I'd like to fix the possible null dereference there too :)

If you can trigger a crash with this, would you please share code that does?

**Comment by Zduniusz** [comment]
Hi,

No crash but it returns as function completed erroneously which screws up my safe assertion. 
I was worried a bit when freeing packet but as it turns out `free(NULL)` has no effect therefore no crash.
