### ISSUE TITLE
libwifi_parse_data zeroes the frame body instead of copying it

### ISSUE THREAD

**Issue by Kriper1111** [libwifi/libwifi#20]
See:
https://github.com/libwifi/libwifi/blob/0a36a1816bd461f7c12867989918435f097895ad/src/libwifi/parse/data/data.c#L41

Which likely was intended to be 
```c
memcpy(data->body, frame->body, data->body_len);
```
as the first operand of  `memcpy` is the destination buffer.

**Comment by foxtrot** [comment]
Fixed with f46a5cc, thanks!
